ITEMS = {
    "Sac": "BAG",
    "Adoube-roi": "2H_CLAYMORE_AVALON",
    "Arbalète": "2H_CROSSBOW",
    "Arbalète à répétition des larmes": "2H_REPEATINGCROSSBOW_UNDEAD",
    "Arbalète légère": "MAIN_1HCROSSBOW",
    "Arbalète lourde": "2H_CROSSBOWLARGE",
    "Arc": "2H_BOW",
    "Arc de Badon": "2H_BOW_KEEPER",
    "Arc de guerre": "2H_WARBOW",
    "Arc de siège": "2H_CROSSBOWLARGE_MORGANA",
    "Arc gémissant": "2H_BOW_HELL",
    "Arc long": "2H_LONGBOW",
    "Arc Marche-ciel": "2H_BOW_CRYSTAL",
    "Arc murmurant": "2H_LONGBOW_UNDEAD",
    "Aria de l'aube": "2H_FIRE_RINGPAIR_AVALON",
    "Barrière Incassable": "OFF_SHIELD_CRYSTAL",
    "Bâton à double tranchant": "2H_DOUBLEBLADEDSTAFF",
    "Bâton arctique": "2H_FROSTSTAFF_CRYSTAL",
    "Bâton ardent": "2H_INFERNOSTAFF_MORGANA",
    "Bâton astral": "2H_ARCANESTAFF_CRYSTAL",
    "Bâton béni": "MAIN_HOLYSTAFF",
    "Bâton braisier": "MAIN_FIRESTAFF_KEEPER",
    "Bâton damné": "MAIN_CURSEDSTAFF",
    "Bâton de créature infernale": "2H_SHAPESHIFTER_HELL",
    "Bâton de feu": "MAIN_FIRESTAFF",
    "Bâton de fléau": "2H_NATURESTAFF_HELL",
    "Bâton de Forgécorce": "MAIN_NATURESTAFF_CRYSTAL",
    "Bâton de gelée blanche": "MAIN_FROSTSTAFF_KEEPER",
    "Bâton de givre": "MAIN_FROSTSTAFF",
    "Bâton de la damnation": "2H_CURSEDSTAFF_MORGANA",
    "Bâton de lune de sang": "2H_SHAPESHIFTER_MORGANA",
    "Bâton de malédiction de vie": "MAIN_CURSEDSTAFF_UNDEAD",
    "Bâton de Marcheflammes": "MAIN_FIRESTAFF_CRYSTAL",
    "Bâton de moine noir": "2H_COMBATSTAFF_MORGANA",
    "Bâton de Putréfaction": "MAIN_CURSEDSTAFF_CRYSTAL",
    "Bâton de rédemption": "2H_HOLYSTAFF_UNDEAD",
    "Bâton de Regard Figé": "2H_SHAPESHIFTER_CRYSTAL",
    "Bâton de sorcellerie": "MAIN_ARCANESTAFF_UNDEAD",
    "Bâton de stalactite": "2H_ICEGAUNTLETS_HELL",
    "Bâton de terre-rune": "2H_SHAPESHIFTER_KEEPER",
    "Bâton de toucher de vie": "MAIN_HOLYSTAFF_MORGANA",
    "Bâton déchu": "2H_HOLYSTAFF_HELL",
    "Bâton démoniaque": "2H_DEMONICSTAFF",
    "Bâton d'équilibre": "2H_ROCKSTAFF_KEEPER",
    "Bâton divin": "2H_DIVINESTAFF",
    "Bâton druidique": "MAIN_NATURESTAFF_KEEPER",
    "Bâton effréné": "2H_NATURESTAFF_KEEPER",
    "Bâton énigmatique": "2H_ENIGMATICSTAFF",
    "Bâton enraciné": "2H_SHAPESHIFTER_SET2",
    "Bâton ésotérique": "MAIN_ARCANESTAFF",
    "Bâton exalté": "2H_HOLYSTAFF_CRYSTAL",
    "Bâton glacial": "2H_GLACIALSTAFF",
    "Bâton infernal": "2H_INFERNOSTAFF",
    "Bâton naturel": "MAIN_NATURESTAFF",
    "Bâton occulte": "2H_ARCANESTAFF_HELL",
    "Bâton primitif": "2H_SHAPESHIFTER_SET3",
    "Bâton rôdeur": "2H_SHAPESHIFTER_SET1",
    "Bâton sans faille": "2H_IRONCLADEDSTAFF",
    "Bâton sauvage": "2H_WILDSTAFF",
    "Bâton souchefer": "MAIN_NATURESTAFF_AVALON",
    "Bâton sulfureux": "2H_FIRESTAFF_HELL",
    "Bec de corbin": "2H_POLEHAMMER",
    "Bouclier": "OFF_SHIELD",
    "Bouclier de scélérat": "OFF_SHIELD_HELL",
    "Bougie de la crypte": "OFF_LAMP_UNDEAD",
    "Brassards de bataille": "2H_KNUCKLES_SET2",
    "Brassards d'Impulsion de Force": "2H_KNUCKLES_CRYSTAL",
    "Brides-furie": "2H_DAGGER_KATAR_AVALON",
    "Brise-face": "OFF_SPIKEDSHIELD_MORGANA",
    "Brise-royaume": "2H_AXE_AVALON",
    "Canne grimaçante": "OFF_JESTERCANE_HELL",
    "Cercle vesperien": "2H_ARCANE_RINGPAIR_AVALON",
    "Cestes-des-freux": "2H_KNUCKLES_MORGANA",
    "Chassesprit": "2H_HARPOON_HELL",
    "Cherchegraal": "2H_QUARTERSTAFF_AVALON",
    "Claymore": "2H_CLAYMORE",
    "Crâne damné": "2H_SKULLORB_HELL",
    "Croc-de-démon": "MAIN_DAGGER_HELL",
    "Dague": "MAIN_DAGGER",
    "Désintégrateurs de Lumière": "2H_DUALCROSSBOW_CRYSTAL",
    "Diurnebris": "MAIN_SPEAR_LANCE_AVALON",
    "Égide astrale": "OFF_SHIELD_AVALON",
    "Encens céleste": "OFF_CENSER_AVALON",
    "Épée double": "2H_DUALSWORD",
    "Épée large": "MAIN_SWORD",
    "Épée tranchante": "2H_CLEAVER_HELL",
    "Fauchâme": "2H_TWINSCYTHE_HELL",
    "Faucheuse de cristal": "2H_SCYTHE_CRYSTAL",
    "Faux infernale": "2H_SCYTHE_HELL",
    "Gantelets à pointes": "2H_KNUCKLES_SET3",
    "Gantelets de bagarreur": "2H_KNUCKLES_SET1",
    "Gardes-serment": "2H_DUALMACE_AVALON",
    "Gardien du bosquet": "2H_RAM_KEEPER",
    "Glaive": "2H_GLAIVE",
    "Glaive déchirant": "2H_GLAIVE_CRYSTAL",
    "Grand bâton béni": "2H_HOLYSTAFF",
    "Grand bâton damné": "2H_CURSEDSTAFF",
    "Grand bâton de feu": "2H_FIRESTAFF",
    "Grand bâton de givre": "2H_FROSTSTAFF",
    "Grand bâton ésotérique": "2H_ARCANESTAFF",
    "Grand bâton naturel": "2H_NATURESTAFF",
    "Grand marteau": "2H_HAMMER",
    "Grande hache": "2H_AXE",
    "Griffes": "2H_CLAWPAIR",
    "Grimoire Chronostatique": "OFF_TOME_CRYSTAL",
    "Hache de guerre": "MAIN_AXE",
    "Hallebarde": "2H_HALBERD",
    "Hurlegivre": "MAIN_FROSTSTAFF_AVALON",
    "Jumelles tueuses": "2H_DAGGERPAIR_CRYSTAL",
    "Lame de Clarent": "MAIN_SCIMITAR_MORGANA",
    "Lame double fantôme": "2H_DOUBLEBLADEDSTAFF_CRYSTAL",
    "Lame infinie": "MAIN_SWORD_CRYSTAL",
    "Lance": "MAIN_SPEAR",
    "Lance de héron": "MAIN_SPEAR_KEEPER",
    "Lance de la trinité": "2H_TRIDENT_UNDEAD",
    "Lanceurs de foudre": "2H_DUALCROSSBOW_HELL",
    "Locus malveillant": "2H_ENIGMATICORB_MORGANA",
    "Long bâton": "2H_QUARTERSTAFF",
    "Main de justice": "2H_HAMMER_AVALON",
    "Mains infernales": "2H_KNUCKLES_HELL",
    "Mains noires": "2H_IRONGAUNTLETS_HELL",
    "Mandebrume": "OFF_HORN_KEEPER",
    "Mande-charogne": "2H_HALBERD_MORGANA",
    "Mande-lumière": "2H_SHAPESHIFTER_AVALON",
    "Mande-ténèbres": "MAIN_CURSEDSTAFF_AVALON",
    "Marteau": "MAIN_HAMMER",
    "Marteau de Foudre": "2H_HAMMER_CRYSTAL",
    "Marteaux forgés": "2H_DUALHAMMER_HELL",
    "Martel-tombe": "2H_HAMMER_UNDEAD",
    "Masse": "MAIN_MACE",
    "Masse de Camlann": "2H_MACE_MORGANA",
    "Masse d'incube": "MAIN_MACE_HELL",
    "Masse du soubassement": "MAIN_ROCKMACE_KEEPER",
    "Masse lourde": "2H_MACE",
    "Matrice d'énergie": "2H_CROSSBOW_CANNON_AVALON",
    "Miniaturisé": "OFF_DEMONSKULL_HELL",
    "Monarque des tempêtes": "MAIN_MACE_CRYSTAL",
    "Morgenstern": "2H_FLAIL",
    "Œil des secrets": "OFF_ORB_MORGANA",
    "Paire de dagues": "2H_DAGGERPAIR",
    "Paire de galatines": "2H_DUALSCIMITAR_UNDEAD",
    "Pattes d'ours": "2H_DUALAXE_KEEPER",
    "Perce-brume": "2H_BOW_AVALON",
    "Pique": "2H_SPEAR",
    "Poignes ursines": "2H_KNUCKLES_KEEPER",
    "Poings d'Avalon": "2H_KNUCKLES_AVALON",
    "Prisme de pergélisol": "2H_ICECRYSTAL_UNDEAD",
    "Racine pivot": "OFF_TOTEM_KEEPER",
    "Sacrificateur": "2H_DUALSICKLE_UNDEAD",
    "Saigneur": "MAIN_RAPIER_MORGANA",
    "Sanctificateur": "MAIN_HOLYSTAFF_AVALON",
    "Sarcophage": "OFF_TOWERSHIELD_UNDEAD",
    "Sceptre sacré": "OFF_TALISMAN_AVALON",
    "Tome de sorts": "OFF_BOOK",
    "Torche": "OFF_TORCH",
    "Torche Flammebleue": "OFF_TORCH_CRYSTAL",
}
RESSOURCES_PAR_ENCHANTEMENT = {
    ".1": ["RUNE"],
    ".2": ["RUNE", "SOUL"],
    ".3": ["RUNE", "SOUL", "RELIC"],
}